### ISSUE TITLE
Replace Webview for Custom Tabs

### ISSUE THREAD

**Issue by carlosrzisc** [BenGoBlue05/UdacityAlumni#33]

**Comment by PPartisan** [comment]
I have a couple of ideas regarding the Custom Tabs:

- We could change the colour of the browser's toolbar with the `setToolbarColor()` method to match the colour of the main app's toolbar, so that the Chrome browser looks even more integrated with the app.

- The documentation mentions it's possible to [pre-load webpages so that they open more quickly](https://developer.chrome.com/multidevice/android/customtabs#implementationguide) to make pages load faster. This might be worth implementing too?

**Comment by chashmeetsingh** [comment]
@PPartisan +1, go ahead with it

**Comment by chashmeetsingh** [comment]
Closing this issue. Resolved by #38
